"""Command-line entrypoint placeholder for AmyloGram-Py."""

from __future__ import annotations

import argparse
import csv
import heapq
import json
from pathlib import Path
import sys
from time import perf_counter

from .fasta import iter_fasta_records
from .lookup import (
    build_probability_table,
    read_probability_table_auto,
    write_probability_table,
    write_probability_table_binary,
)
from .model import load_amylogram_model
from .predict import predict_clean_sequence_probability, probability_to_label
from .provenance import sha256_file


def load_probability_table(path: str | Path) -> list[float]:
    return read_probability_table_auto(path)


def write_prediction_report(
    path: str | Path,
    metrics: dict[str, object],
) -> None:
    lines = [
        "# AmyloGram-Py Prediction Report",
        "",
        "This report was generated by `amylogram-py`.",
        "",
        "## Inputs",
        "",
        f"- Input FASTA: `{metrics['input_fasta']}`",
        f"- Input FASTA SHA256: `{metrics['input_fasta_sha256']}`",
        f"- Output CSV: `{metrics['output_csv']}`",
        f"- Six-mer table: `{metrics['sixmer_table']}`",
        f"- Six-mer table SHA256: `{metrics['sixmer_table_sha256']}`",
        f"- Threshold: `{metrics['threshold']}`",
        "",
        "## Metrics",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Total FASTA records | {metrics['total_records']} |",
        f"| Predicted records | {metrics['predicted_records']} |",
        f"| Skipped records | {metrics['skipped_records']} |",
        f"| Amyloid predictions | {metrics['amyloid_records']} |",
        f"| Non-amyloid predictions | {metrics['non_amyloid_records']} |",
        f"| Mean probability | {float(metrics['mean_probability']):.6f} |",
        f"| Max probability | {float(metrics['max_probability'] or 0.0):.6f} |",
        f"| Elapsed seconds | {float(metrics['elapsed_seconds']):.6f} |",
        f"| Predicted records per second | {float(metrics['predicted_records_per_second']):.2f} |",
        "",
    ]
    if metrics["max_sequence_id"] is not None:
        lines.extend(
            [
                "## Top Signal",
                "",
                f"- Max sequence ID: `{metrics['max_sequence_id']}`",
                f"- Top-K TSV: `{metrics['top_tsv']}`",
                "",
            ]
        )
    Path(path).write_text("\n".join(lines), encoding="utf-8")


def write_prediction_report_json(path: str | Path, metrics: dict[str, object]) -> None:
    Path(path).write_text(json.dumps(metrics, indent=2, sort_keys=True), encoding="utf-8")


def write_top_hits_tsv(path: str | Path, hits: list[tuple[float, str, str]]) -> None:
    rows = sorted(hits, key=lambda item: (-item[0], item[1]))
    with Path(path).open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=["Rank", "Sequence_ID", "AmyloGram_Prob", "AmyloGram_Pred"],
            delimiter="\t",
        )
        writer.writeheader()
        for rank, (probability, sequence_id, label) in enumerate(rows, start=1):
            writer.writerow(
                {
                    "Rank": rank,
                    "Sequence_ID": sequence_id,
                    "AmyloGram_Prob": f"{probability:.10g}",
                    "AmyloGram_Pred": label,
                }
            )


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if argv and argv[0] == "build-table":
        parser = argparse.ArgumentParser(description="Build an AmyloGram-Py 6-mer lookup table")
        parser.add_argument("command")
        parser.add_argument("model_json", help="JSON exported from R AmyloGram")
        parser.add_argument("output_table", help="Output lookup table")
        parser.add_argument(
            "--format",
            choices=["auto", "json", "bin"],
            default="auto",
            help="Output table format. Auto uses .bin for binary and JSON otherwise.",
        )
        args = parser.parse_args(argv)

        model = load_amylogram_model(args.model_json)
        table = build_probability_table(model.forest, model.imp_features)
        output_format = args.format
        if output_format == "auto":
            output_format = "bin" if str(args.output_table).endswith(".bin") else "json"
        if output_format == "bin":
            write_probability_table_binary(table, args.output_table)
        else:
            write_probability_table(table, args.output_table)
        return 0

    parser = argparse.ArgumentParser(description="Predict amyloidogenicity with AmyloGram-Py")
    parser.add_argument("input_fasta")
    parser.add_argument("output_csv")
    parser.add_argument("--sixmer-table", required=True, help="JSON or binary table with 46656 six-mer probabilities")
    parser.add_argument("--threshold", type=float, default=0.5)
    parser.add_argument("--report-md", help="Write a Markdown prediction report")
    parser.add_argument("--report-json", help="Write a machine-readable JSON prediction report")
    parser.add_argument("--skipped-tsv", help="Write skipped FASTA records and reasons")
    parser.add_argument("--top-k", type=int, default=0, help="Number of highest-probability records to keep")
    parser.add_argument("--top-tsv", help="Write top-K predictions to a TSV file")
    args = parser.parse_args(argv)
    if args.top_k < 0:
        parser.error("--top-k must be non-negative")
    if args.top_tsv and args.top_k == 0:
        parser.error("--top-tsv requires --top-k > 0")

    start = perf_counter()
    table = load_probability_table(args.sixmer_table)
    total_records = 0
    predicted_records = 0
    skipped_records = 0
    amyloid_records = 0
    non_amyloid_records = 0
    probability_sum = 0.0
    max_probability: float | None = None
    max_sequence_id: str | None = None
    top_hits: list[tuple[float, str, str]] = []

    skipped_handle = None
    skipped_writer = None
    if args.skipped_tsv:
        skipped_handle = Path(args.skipped_tsv).open("w", newline="", encoding="utf-8")
        skipped_writer = csv.DictWriter(
            skipped_handle,
            fieldnames=["Sequence_ID", "Raw_Length", "Clean_Length", "Reason"],
            delimiter="\t",
        )
        skipped_writer.writeheader()

    with Path(args.output_csv).open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=["Sequence_ID", "AmyloGram_Prob", "AmyloGram_Pred"])
        writer.writeheader()
        for record in iter_fasta_records(args.input_fasta):
            total_records += 1
            if record.status != "ok":
                skipped_records += 1
                if skipped_writer is not None:
                    skipped_writer.writerow(
                        {
                            "Sequence_ID": record.sequence_id,
                            "Raw_Length": record.raw_length,
                            "Clean_Length": record.clean_length,
                            "Reason": record.reason,
                        }
                    )
                continue

            probability = predict_clean_sequence_probability(record.sequence, table)
            label = probability_to_label(probability, args.threshold)
            predicted_records += 1
            probability_sum += probability
            if max_probability is None or probability > max_probability:
                max_probability = probability
                max_sequence_id = record.sequence_id
            if args.top_k:
                entry = (probability, record.sequence_id, label)
                if len(top_hits) < args.top_k:
                    heapq.heappush(top_hits, entry)
                elif entry > top_hits[0]:
                    heapq.heapreplace(top_hits, entry)
            if label == "AMYLOID":
                amyloid_records += 1
            else:
                non_amyloid_records += 1
            writer.writerow(
                {
                    "Sequence_ID": record.sequence_id,
                    "AmyloGram_Prob": f"{probability:.10g}",
                    "AmyloGram_Pred": label,
                }
            )
    if skipped_handle is not None:
        skipped_handle.close()

    elapsed_seconds = perf_counter() - start
    throughput = predicted_records / elapsed_seconds if elapsed_seconds > 0 else 0.0
    mean_probability = probability_sum / predicted_records if predicted_records else 0.0
    if args.top_tsv:
        write_top_hits_tsv(args.top_tsv, top_hits)
    metrics: dict[str, object] = {
        "input_fasta": str(args.input_fasta),
        "input_fasta_sha256": sha256_file(args.input_fasta),
        "output_csv": str(args.output_csv),
        "sixmer_table": str(args.sixmer_table),
        "sixmer_table_sha256": sha256_file(args.sixmer_table),
        "threshold": float(args.threshold),
        "total_records": total_records,
        "predicted_records": predicted_records,
        "skipped_records": skipped_records,
        "amyloid_records": amyloid_records,
        "non_amyloid_records": non_amyloid_records,
        "mean_probability": mean_probability,
        "max_probability": max_probability,
        "max_sequence_id": max_sequence_id,
        "top_k": args.top_k,
        "top_tsv": str(args.top_tsv) if args.top_tsv else None,
        "elapsed_seconds": elapsed_seconds,
        "predicted_records_per_second": throughput,
    }
    if args.report_md:
        write_prediction_report(args.report_md, metrics=metrics)
    if args.report_json:
        write_prediction_report_json(args.report_json, metrics=metrics)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
