#!/usr/bin/env bash
set -Eeuo pipefail

script="${1:-/home/codex/run_amyloid_predictors.sh}"

test -s "$script"
bash -n "$script"
grep -q 'run_amypred' "$script"
grep -q 'run_amylogram' "$script"
grep -q 'run_amylogram_py' "$script"
grep -q 'run_protein_features' "$script"
grep -q 'merge_predictions' "$script"
grep -q 'amyloid_combined_predictions.csv' "$script"
grep -q 'protein_features.csv' "$script"
grep -q 'PROTEIN_FEATURES_OUTPUT_S3' "$script"
grep -q 'AMYLOGRAM_CHUNK_SIZE="${AMYLOGRAM_CHUNK_SIZE:-200}"' "$script"
grep -q 'AMYLOGRAM_RETRY_SPLIT_DEPTH="${AMYLOGRAM_RETRY_SPLIT_DEPTH:-10}"' "$script"
grep -q 'AMYLOGRAM_ALLOW_ERRORS="${AMYLOGRAM_ALLOW_ERRORS:-0}"' "$script"
grep -q -- '-e AMYLOGRAM_RETRY_SPLIT_DEPTH="${AMYLOGRAM_RETRY_SPLIT_DEPTH}"' "$script"
grep -q -- '-e AMYLOGRAM_ALLOW_ERRORS="${AMYLOGRAM_ALLOW_ERRORS}"' "$script"
grep -q 'predict_amylogram_fast.R' "$script"
grep -q 'RUN_AMYLOGRAM_PY="${RUN_AMYLOGRAM_PY:-1}"' "$script"
grep -q 'AMYLOGRAM_PY_IMAGE="${AMYLOGRAM_PY_IMAGE:-amylogram-py:local}"' "$script"
grep -q 'AMYLOGRAM_PY_LOOKUP' "$script"
grep -q 'amylogram_py_prediction.csv' "$script"
grep -q 'amylogram_py_report.json' "$script"
grep -q 'amylogram_py_top_hits.tsv' "$script"
grep -q -- '--run-amylogram-py' "$script"
grep -q 'PROTEIN_FEATURES_IMAGE' "$script"
grep -q 'PROTEIN_FEATURES_WINDOW="${PROTEIN_FEATURES_WINDOW:-7}"' "$script"
grep -q 'PROTEIN_FEATURES_PH="${PROTEIN_FEATURES_PH:-7.0}"' "$script"
grep -q 'PROTEIN_FEATURES_R_LIBS="${PROTEIN_FEATURES_R_LIBS:-}"' "$script"
grep -q 'calc_protein_features.R' "$script"
grep -q -- '--run-protein-features' "$script"
grep -q -- '--skip-protein-features' "$script"
grep -q -- '--protein-features-output-s3' "$script"

echo "run_amyloid_predictors static checks OK"
