#!/usr/bin/env python3
"""Reproduce AmyloGram-Py parity checks against exported R AmyloGram fixtures."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


PROJECT = Path(__file__).resolve().parents[1]
SRC = PROJECT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from amylogram_py.encoding import encode_groups, sixmer_code  # noqa: E402
from amylogram_py.features import feature_vector_for_code  # noqa: E402
from amylogram_py.lookup import read_probability_table  # noqa: E402
from amylogram_py.model import load_amylogram_model  # noqa: E402
from amylogram_py.predict import (  # noqa: E402
    predict_sequence_probability,
    predict_sequence_probability_from_model,
)


FIXTURE = PROJECT / "tests" / "fixtures" / "amylogram_reference.json"
LOOKUP = PROJECT / "tests" / "fixtures" / "amylogram_sixmer_probabilities.json"
MAX_ALLOWED_DELTA = 5e-4


def build_rows() -> tuple[list[dict[str, object]], int]:
    payload = json.loads(FIXTURE.read_text(encoding="utf-8"))
    model = load_amylogram_model(FIXTURE)
    table = read_probability_table(LOOKUP)

    rows: list[dict[str, object]] = []
    failed = False
    for example in payload["examples"]:
        sequence = str(example["sequence"])
        code = sixmer_code(encode_groups(sequence[:6]))
        py_features = feature_vector_for_code(code)
        r_features = [int(value) for value in example["all_feature_values"]]
        mismatches = sum(left != right for left, right in zip(py_features, r_features))

        py_forest = predict_sequence_probability_from_model(sequence, model)
        py_lookup = predict_sequence_probability(sequence, table)
        r_probability = float(example["probability"])
        forest_delta = py_forest - r_probability
        lookup_delta = py_lookup - r_probability

        status = "OK"
        if mismatches != 0 or abs(forest_delta) > MAX_ALLOWED_DELTA or abs(lookup_delta) > MAX_ALLOWED_DELTA:
            status = "FAIL"
            failed = True

        rows.append(
            {
                "id": str(example["id"]),
                "sequence": sequence,
                "feature_mismatches": mismatches,
                "r_probability": r_probability,
                "python_forest": py_forest,
                "python_lookup": py_lookup,
                "forest_delta": forest_delta,
                "lookup_delta": lookup_delta,
                "status": status,
            }
        )

    return rows, 1 if failed else 0


def print_rows(rows: list[dict[str, object]]) -> None:
    table = read_probability_table(LOOKUP)
    print(f"R fixture: {FIXTURE.relative_to(PROJECT)}")
    print(f"Lookup table: {LOOKUP.relative_to(PROJECT)}")
    print(f"Lookup entries: {len(table)}")
    print()
    print(
        "\t".join(
            [
                "ID",
                "feature_mismatches",
                "R_probability",
                "Python_forest",
                "Python_lookup",
                "forest_delta",
                "lookup_delta",
                "status",
            ]
        )
    )

    for row in rows:
        print(
            "\t".join(
                [
                    str(row["id"]),
                    str(row["feature_mismatches"]),
                    f"{float(row['r_probability']):.6f}",
                    f"{float(row['python_forest']):.6f}",
                    f"{float(row['python_lookup']):.6f}",
                    f"{float(row['forest_delta']):+.6g}",
                    f"{float(row['lookup_delta']):+.6g}",
                    str(row["status"]),
                ]
            )
        )


def write_markdown_report(rows: list[dict[str, object]], output_path: Path) -> None:
    total = len(rows)
    failed = sum(1 for row in rows if row["status"] != "OK")
    max_feature_mismatches = max(int(row["feature_mismatches"]) for row in rows)
    max_abs_forest_delta = max(abs(float(row["forest_delta"])) for row in rows)
    max_abs_lookup_delta = max(abs(float(row["lookup_delta"])) for row in rows)
    lookup_entries = len(read_probability_table(LOOKUP))

    lines = [
        "# AmyloGram-Py Parity Evidence",
        "",
        "This report was generated by `evidence/run_parity_checks.py`.",
        "",
        "## Inputs",
        "",
        f"- R fixture: `{FIXTURE.relative_to(PROJECT)}`",
        f"- Lookup table: `{LOOKUP.relative_to(PROJECT)}`",
        f"- Lookup entries: `{lookup_entries}`",
        f"- Accepted probability tolerance: `{MAX_ALLOWED_DELTA:g}`",
        "",
        "## Summary Metrics",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Examples checked | {total} |",
        f"| Failed examples | {failed} |",
        f"| Max feature mismatches | {max_feature_mismatches} |",
        f"| Max abs forest delta | {max_abs_forest_delta:.6g} |",
        f"| Max abs lookup delta | {max_abs_lookup_delta:.6g} |",
        "",
        "## Per-Example Results",
        "",
        "| ID | Sequence | Feature mismatches | R probability | Python forest | Python lookup | Forest delta | Lookup delta | Status |",
        "|---|---|---:|---:|---:|---:|---:|---:|---|",
    ]

    for row in rows:
        lines.append(
            "| {id} | `{sequence}` | {feature_mismatches} | {r_probability:.6f} | "
            "{python_forest:.6f} | {python_lookup:.6f} | {forest_delta:+.6g} | "
            "{lookup_delta:+.6g} | {status} |".format(
                id=row["id"],
                sequence=row["sequence"],
                feature_mismatches=row["feature_mismatches"],
                r_probability=float(row["r_probability"]),
                python_forest=float(row["python_forest"]),
                python_lookup=float(row["python_lookup"]),
                forest_delta=float(row["forest_delta"]),
                lookup_delta=float(row["lookup_delta"]),
                status=row["status"],
            )
        )

    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- `feature_mismatches = 0` means Python reproduces the R `biogram` feature vector exactly.",
            "- `Python_forest` is computed by traversing the exported R `ranger` forest in Python.",
            "- `Python_lookup` is computed from the precomputed `46656`-entry 6-mer probability table.",
            "- Small probability deltas are expected because the R fixture stores rounded display probabilities.",
            "",
            "## Reproduce",
            "",
            "```bash",
            "python3 evidence/run_parity_checks.py --report evidence/amylogram_parity_report.md",
            "```",
            "",
            "Focused tests:",
            "",
            "```bash",
            "PYTHONPATH=src python3 -m unittest \\",
            "  tests.test_features \\",
            "  tests.test_model \\",
            "  tests.test_lookup \\",
            "  tests.test_predict \\",
            "  -v",
            "```",
            "",
        ]
    )

    output_path.write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Check AmyloGram-Py parity and generate Markdown evidence.")
    parser.add_argument(
        "--report",
        default=str(PROJECT / "evidence" / "amylogram_parity_report.md"),
        help="Path for the generated Markdown report.",
    )
    args = parser.parse_args(argv)

    rows, exit_code = build_rows()
    print_rows(rows)
    write_markdown_report(rows, Path(args.report))
    print()
    print(f"Markdown report written: {Path(args.report)}")
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
